[target.x86_64-unknown-linux-gnu]
linker = "C:\\build\\2023\\x64\\sysroots\\x86_64-w64-mingw32\\usr\\bin\\x86_64-nilrt-linux\\x86_64-nilrt-linux-gcc"
#ar = "C:\\build\\2023\\x64\\sysroots\\x86_64-w64-mingw32\\usr\\bin\\x86_64-nilrt-linux\\x86_64-nilrt-linux-ar"
rustflags = [
"-C", "link-arg=--sysroot=C:\\build\\2023\\x64\\sysroots\\core2-64-nilrt-linux"
]

[target.armv7-unknown-linux-gnueabi]
linker = "C:\\build\\18.0\\arm\\sysroots\\i686-nilrtsdk-mingw32\\usr\\bin\\arm-nilrt-linux-gnueabi\\arm-nilrt-linux-gnueabi-gcc"
rustflags = [
"-C", "link-arg=-march=armv7-a",
"-C", "link-arg=-mfpu=vfpv3",
"-C", "link-arg=-mfloat-abi=softfp",
"-C", "link-arg=-mcpu=cortex-a9",
"-C", "link-arg=--sysroot=C:\\build\\18.0\\arm\\sysroots\\cortexa9-vfpv3-nilrt-linux-gnueabi"
]